# Generated by Django 5.0.3 on 2024-03-14 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_asset', '0002_alter_company_contact_number_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20, null=True)),
                ('price', models.IntegerField(null=True)),
                ('serial_number', models.CharField(max_length=50)),
                ('condition_lent', models.TextField(null=True)),
                ('condition_returned', models.TextField(null=True)),
                ('return_by', models.DateField(null=True)),
                ('returned_at', models.DateField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='corporate_asset.company')),
                ('lent_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lent_devices', to='corporate_asset.employee')),
            ],
        ),
    ]
