# Generated by Django 5.0.3 on 2024-03-14 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_asset', '0003_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='lent_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lent_assets', to='corporate_asset.employee'),
        ),
    ]
