# Generated by Django 5.0.3 on 2024-03-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_asset', '0004_alter_asset_lent_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
    ]
