# Generated by Django 5.0.3 on 2024-03-15 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_asset', '0006_alter_asset_condition_lent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='lent_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lent_assets', to='corporate_asset.employee'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
