# Generated by Django 5.0.3 on 2024-03-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_asset', '0008_assetlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlog',
            name='condition_lent',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetlog',
            name='condition_returned',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
