# Generated by Django 5.0.3 on 2024-03-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_asset', '0009_assetlog_condition_lent_assetlog_condition_returned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetlog',
            old_name='employee',
            new_name='lent_to',
        ),
    ]
