# Generated by Django 5.0.3 on 2024-03-16 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_asset', '0012_assetlog_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlog',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asset_log', to='corporate_asset.asset'),
            preserve_default=False,
        ),
    ]
